### PR TITLE
[AD-61] Make REPL widget omnipresent

### PR DESCRIPTION
**Pull request by goodsoft**
Much disputable very don't merge wow

### CODE REVIEW

**Comment by gromakovsky** [comment]
We decided to make this widget omnipresent (btw, not really, I don't think it should be in `About`) and only show the last command in REPL output (to make it smaller).

**Comment by goodsoft** [comment]
Not anymore, we discussed it with Gromak and Rukin and decided it's OK.

**Comment by gromakovsky** [comment]
• `stack exec ariadne`
• `Esc-L`
• `Esc-R`

After that I am in `Wallet`. Is it intended?

**Comment by goodsoft** [comment]
Probably not, will fix.

**Pull request merged**
