### PR TITLE
[OPS-322] fail on hlint warnings

### PR DESCRIPTION
**Pull request by yorickvP**

### CODE REVIEW

**Comment by gromakovsky** [comment]
Default hlint rules are usually not suitable out-of-box. We need to come up with ariadne-specific rules first.

**Comment by Pastafarianist** [comment]
We'll have to review these hints later. For now, do I understand correctly that `hlint` does not currently run on `ariadne-vty`? If so, can you enable it?

**Comment by maksbotan** [comment]
Would be great if you somehow automatically annotaded PR lines, in addition to just providing the log. In the current form it's not very comfortable to use.

**Comment by yorickvP** [comment]
I considered exposing the html report, but it would not be nearly as good
as people running hlint themselves. The main purpose of doing it in the CI
is to make it fail when there are errors.
GitHub supports some annotation thing nowadays, I wouldn't count on devtime
being spent on using that.

**Comment by Pastafarianist** [comment]
Blocked until https://issues.serokell.io/issue/AD-285 is resolved.

**Comment by mkaito** [comment]
When merged, update https://issues.serokell.io/issue/OPS-322

**Comment by Pastafarianist** [comment]
Updated the issue. Also commenting here to ensure that this does not slip through the cracks.

**Comment by gromakovsky** [comment]
AFAIU it's done and the issue can be closed.

**Pull request closed without merging**
