### PR TITLE
[AD-109] Extract TUI/Qt into separate Cabal files

### PR DESCRIPTION
**Pull request by maksbotan**
This will allow Windows CI to build only ariadne-qt with stack,
as `vty` library can't be built on Windows.

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
@yorickvP Sounds good to me.

**Comment by maksbotan** [comment]
Note that TUI is now separate as well, so you probably need to build all three packages: `ariadne`, `ariadne-vty`, `ariadne-qt`.

**Comment by gromakovsky** [comment]
@yorickvP @yegortimoshenko can you do it please? :pray:

**Comment by gromakovsky** [comment]
I'll re-review when CI passes.

**Pull request merged**
